In [17]:
import numpy as np 
walls = np.ones((5, 2, 2))
for i in range(walls.shape[0]):
    walls[i][0] *= 2*i
    walls[i][1] *= 2*i + 1
walls

array([[[0., 0.],
        [1., 1.]],

       [[2., 2.],
        [3., 3.]],

       [[4., 4.],
        [5., 5.]],

       [[6., 6.],
        [7., 7.]],

       [[8., 8.],
        [9., 9.]]])

In [18]:
A = walls[:,0,:]

A.shape

(5, 2)

In [19]:
A

array([[0., 0.],
       [2., 2.],
       [4., 4.],
       [6., 6.],
       [8., 8.]])

In [20]:
B=A*A
B

array([[ 0.,  0.],
       [ 4.,  4.],
       [16., 16.],
       [36., 36.],
       [64., 64.]])

In [21]:
uTop = np.sum( A, axis=1)
uTop

array([ 0.,  4.,  8., 12., 16.])

In [22]:
 A = np.expand_dims(walls[:,0,:], axis= 0)
 A

array([[[0., 0.],
        [2., 2.],
        [4., 4.],
        [6., 6.],
        [8., 8.]]])

In [23]:
radar_angles = np.array([[315.0, 405.0], [45.0, 135.0], [135.0, 225.0], [225.0, 315.0]])
heading = 60
radar_angles = (radar_angles + heading) 
radar_angles

array([[375., 465.],
       [105., 195.],
       [195., 285.],
       [285., 375.]])

In [24]:
radar_range = radar_angles[:,1]-radar_angles[:,0]
radar_range

array([90., 90., 90., 90.])

In [25]:
radar_angles.shape[0]


4

In [26]:
import numpy as np

# サンプル配列の用意
a = np.arange(10).reshape(2, 5)
b = np.arange(15).reshape(3, 5)
c = np.arange(8).reshape(2, 4)
d = list(range(5))

# 配列をprintして中身を確認
print("a")
print(a)
print("b")
print(b)
print("c")
print(c)
print("d")
print(d)


a
[[0 1 2 3 4]
 [5 6 7 8 9]]
b
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
c
[[0 1 2 3]
 [4 5 6 7]]
d
[0, 1, 2, 3, 4]


In [27]:
range_finder_angles = np.array([-90.0, -45.0, 0.0, 45.0, 90.0, -180.0])
range_finder_angles = range_finder_angles / 180 * np.pi

r = 100.0
finder_direction=[np.cos(range_finder_angles), np.sin(range_finder_angles)]
finder_direction

[array([ 6.12323400e-17,  7.07106781e-01,  1.00000000e+00,  7.07106781e-01,
         6.12323400e-17, -1.00000000e+00]),
 array([-1.00000000e+00, -7.07106781e-01,  0.00000000e+00,  7.07106781e-01,
         1.00000000e+00, -1.22464680e-16])]

In [28]:
range_finder_angles = np.array([-90.0, -45.0, 0.0, 45.0, 90.0, -180.0])
range_finder_angles = range_finder_angles / 180 * np.pi

r = 100.0
finder_rad=np.vstack([np.cos(range_finder_angles), np.sin(range_finder_angles)])
finder_rad

array([[ 6.12323400e-17,  7.07106781e-01,  1.00000000e+00,
         7.07106781e-01,  6.12323400e-17, -1.00000000e+00],
       [-1.00000000e+00, -7.07106781e-01,  0.00000000e+00,
         7.07106781e-01,  1.00000000e+00, -1.22464680e-16]])

In [29]:
finder_rad = (finder_rad).T
finder_rad

array([[ 6.12323400e-17, -1.00000000e+00],
       [ 7.07106781e-01, -7.07106781e-01],
       [ 1.00000000e+00,  0.00000000e+00],
       [ 7.07106781e-01,  7.07106781e-01],
       [ 6.12323400e-17,  1.00000000e+00],
       [-1.00000000e+00, -1.22464680e-16]])

In [34]:
def update_radars(exit_point, location, radar_angles):
        
        # ゴールとロボットの角度をアークタンジェントで求めてpiで割ったあまり
        exit_angle = np.arctan2(exit_point[0]-location[0], exit_point[1]-location[1]) % np.pi 
        
        # ロボットの頭の向き分レーダーの角度範囲をすべてずらし，ラジアンに
        radar_angles = (radar_angles + heading) /180 *np.pi

        # 各レーダーの幅に変換
        radar_range = radar_angles[:,1]-radar_angles[:,0]
        # レーダー範囲の早い方との差を出し，2piで割った余りにすることで１周以内で表す
        radar_diff = (exit_angle-radar_angles[:,0])%(2*np.pi)
        # radar_anglesの行数と同じ要素数の0で初期化された配列を作る
        radar = np.zeros(radar_angles.shape[0])
        # レーダーとの差がレーダーの範囲以内だったらそのレーダーに対応する要素を１にする
        radar[radar_diff<radar_range] = 1
        radar = radar
        print(radar)

In [43]:
e = (0,0)
l = (1, 1)
radar_angles = np.array([[315.0, 405.0], [45.0, 135.0], [135.0, 225.0], [225.0, 315.0]])
heading = 120
update_radars(e, l, radar_angles)

[0. 0. 0. 1.]
