In [2]:
import numpy as np
import sys
import os

body = np.loadtxt(f'test.txt')
body

array([[2., 0., 0., 0., 0.],
       [1., 0., 0., 1., 1.],
       [4., 3., 3., 3., 4.],
       [4., 3., 1., 3., 4.],
       [4., 0., 0., 0., 4.]])

In [3]:
body.shape[1]
# 配列の１行目の要素数

5

In [4]:
body.size

25

In [5]:
for i in range(body.size):
    x = i % body.shape

TypeError: unsupported operand type(s) for %: 'int' and 'tuple'

In [6]:
# utils.py 230行あたり
out =[]
for i in range(body.size):
    x = i % body.shape[1] # 
    y = i // body.shape[1]
    
    if body[y][x] == 0:
        continue
    
    nx = x + 1
    ny = y
    
    if x >= 0 and y >= 0 and x < body.shape[0]-1 and y < body.shape[1]-1 and body[ny][nx] != 0:
        out.append( [x + y * body.shape[1], nx + ny * body.shape[1]] )
    
    nx = x
    ny = y + 1

    if x >= 0 and y >= 0 and x < body.shape[0]-1 and y < body.shape[1]-1 and body[ny][nx] != 0:
        out.append([x + body.shape[1] * y, nx + body.shape[1] * ny])
    
np.array(out).T
    

array([[ 0,  5,  8,  8, 10, 10, 11, 11, 12, 12, 13, 13, 15, 15, 16, 17,
        18],
       [ 5, 10,  9, 13, 11, 15, 12, 16, 13, 17, 14, 18, 16, 20, 17, 18,
        19]])

In [ ]:
np.empty((0, 2)).T

array([], shape=(2, 0), dtype=float64)

In [ ]:
def get_full_connectivity(robot: np.ndarray) -> np.ndarray:
    out = []

    for i in range(robot.size): # 配列bodyの要素数分の繰り返し
        #　bodyの要素は部品の設定の記号でその要素が何行何列にあるかで一が決められているため行，列数を調べる
        x = i % robot.shape[1] # 
        y = i // robot.shape[1]

        if robot[y][x] == 0: # 部品のない部分を飛ばす
            continue

        nx = x + 1
        ny = y

        # 
        if nx < 5 and ny < 5 and nx >= 0 and ny >= 0 and robot[ny][nx] != 0:
            # 
            out.append([x + robot.shape[1] * y, nx + robot.shape[1] * ny])

        nx = x
        ny = y + 1

        if nx < 5 and ny < 5 and nx >= 0 and ny >= 0 and robot[ny][nx] != 0:
            out.append([x + robot.shape[1] * y, nx + robot.shape[1] * ny])

    if len(out) == 0:
        return np.empty((0, 2)).T
    return np.array(out).T

In [ ]:
get_full_connectivity(body)

array([[ 0,  5,  8,  8,  9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 15, 15,
        16, 17, 18, 19],
       [ 5, 10,  9, 13, 14, 11, 15, 12, 16, 13, 17, 14, 18, 19, 16, 20,
        17, 18, 19, 24]])