In [1]:
import numpy as np

In [2]:
np.random.seed(123)
np.random.uniform()

0.6964691855978616

In [3]:
np.random.uniform()

0.28613933495037946

In [4]:
size = [5,5]
x, y = np.meshgrid(np.arange(size[0]), np.arange(size[1]), indexing='ij')

In [5]:
x,y


(array([[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]]),
 array([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]))

In [6]:
x = x.flatten()
x

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4])

In [7]:
y = y.flatten()

In [8]:
np.array(size)

array([5, 5])

In [9]:
np.array(size)-1

array([4, 4])

In [10]:
np.array([4, 4])/4

array([1., 1.])

In [11]:
center = (np.array(size)-1)/2
center

array([2., 2.])

In [12]:
d = np.sqrt(np.square(x - center[0]) + np.square(y - center[1]))
d

array([2.82842712, 2.23606798, 2.        , 2.23606798, 2.82842712,
       2.23606798, 1.41421356, 1.        , 1.41421356, 2.23606798,
       2.        , 1.        , 0.        , 1.        , 2.        ,
       2.23606798, 1.41421356, 1.        , 1.41421356, 2.23606798,
       2.82842712, 2.23606798, 2.        , 2.23606798, 2.82842712])

In [13]:
x-center[0]

array([-2., -2., -2., -2., -2., -1., -1., -1., -1., -1.,  0.,  0.,  0.,
        0.,  0.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  2.])

In [14]:
np.vstack([x, y, d])

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        2.        , 2.        , 2.        , 2.        , 2.        ,
        3.        , 3.        , 3.        , 3.        , 3.        ,
        4.        , 4.        , 4.        , 4.        , 4.        ],
       [0.        , 1.        , 2.        , 3.        , 4.        ,
        0.        , 1.        , 2.        , 3.        , 4.        ,
        0.        , 1.        , 2.        , 3.        , 4.        ,
        0.        , 1.        , 2.        , 3.        , 4.        ,
        0.        , 1.        , 2.        , 3.        , 4.        ],
       [2.82842712, 2.23606798, 2.        , 2.23606798, 2.82842712,
        2.23606798, 1.41421356, 1.        , 1.41421356, 2.23606798,
        2.        , 1.        , 0.        , 1.        , 2.        ,
        2.23606798, 1.41421356, 1.        , 1.41421356, 2.23606798,
        2.82842712, 2.23606798, 2.        , 2.

In [15]:
np.vstack([x, y, d]).T

array([[0.        , 0.        , 2.82842712],
       [0.        , 1.        , 2.23606798],
       [0.        , 2.        , 2.        ],
       [0.        , 3.        , 2.23606798],
       [0.        , 4.        , 2.82842712],
       [1.        , 0.        , 2.23606798],
       [1.        , 1.        , 1.41421356],
       [1.        , 2.        , 1.        ],
       [1.        , 3.        , 1.41421356],
       [1.        , 4.        , 2.23606798],
       [2.        , 0.        , 2.        ],
       [2.        , 1.        , 1.        ],
       [2.        , 2.        , 0.        ],
       [2.        , 3.        , 1.        ],
       [2.        , 4.        , 2.        ],
       [3.        , 0.        , 2.23606798],
       [3.        , 1.        , 1.41421356],
       [3.        , 2.        , 1.        ],
       [3.        , 3.        , 1.41421356],
       [3.        , 4.        , 2.23606798],
       [4.        , 0.        , 2.82842712],
       [4.        , 1.        , 2.23606798],
       [4.

In [16]:
rng = np.random.default_rng()
arr = rng.integers(1, 10, (5, 10))
arr

array([[6, 3, 2, 5, 3, 1, 8, 8, 3, 2],
       [6, 9, 7, 3, 8, 5, 1, 6, 3, 6],
       [6, 8, 2, 8, 9, 7, 7, 5, 1, 3],
       [1, 7, 5, 6, 4, 5, 2, 3, 4, 1],
       [7, 1, 2, 1, 7, 1, 2, 3, 4, 3]])

In [17]:
x = np.zeros(10, dtype=int)
np.argmax(arr, axis=0, out=x)

array([4, 1, 1, 2, 2, 2, 0, 0, 3, 1])

In [18]:
print(np.reshape(x, [2,5]))

[[4 1 1 2 2]
 [2 0 0 3 1]]


In [19]:
robot=np.array([[2., 0., 0., 0., 0.],
       [1., 0., 0., 1., 1.],
       [4., 3., 3., 3., 4.],
       [4., 3., 1., 3., 4.],
       [4., 0., 0., 0., 4.]])

In [20]:
def hashable(robot: np.ndarray) -> str:
    """
    ロボットのハッシュ可能な表現を返す。

    引数
        robot (np.ndarray): ロボットのボクセル構造を指定する配列。
    
    戻り値
        str: ロボットの文字列表現。

    """
    out = ""
    for i in range(robot.shape[0]):
        for j in range(robot.shape[1]):
            out += str(int(robot[i][j]))
    
    return out

In [21]:
robot_hash = hashable(robot)
robot_hash

'2000010011433344313440004'

In [22]:
hash = {}

In [23]:
hash[robot_hash] = True

In [24]:
hash

{'2000010011433344313440004': True}

In [25]:
if robot_hash in hash:
    print(robot_hash)
else:
    print(False)

2000010011433344313440004


In [26]:
start = (3,9)

In [27]:
start[1]

9

In [28]:
out = [[1,2,3,4,5],
       [1,2,3,4,5],
       [1,2,3,4,5]]

In [29]:
np.argmax(out, axis=1) #インデックス番号が返る

array([4, 4, 4])